name: screenshot-desktop

on:
  workflow_dispatch:

jobs:
  capture:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Take screenshot
      shell: powershell
      run: |
        Add-Type -AssemblyName System.Windows.Forms
        Add-Type -AssemblyName System.Drawing

        $bmp = New-Object System.Drawing.Bitmap([System.Windows.Forms.SystemInformation]::VirtualScreen.Width,
                                               [System.Windows.Forms.SystemInformation]::VirtualScreen.Height)
        $graphics = [System.Drawing.Graphics]::FromImage($bmp)
        $graphics.CopyFromScreen([System.Windows.Forms.SystemInformation]::VirtualScreen.X,
                                 [System.Windows.Forms.SystemInformation]::VirtualScreen.Y, 0, 0,
                                 $bmp.Size)
        $bmp.Save("$env:GITHUB_WORKSPACE\screenshot.png")

    - name: Upload screenshot
      uses: actions/upload-artifact@v3
      with:
        name: desktop-screenshot
        path: screenshot.png
